# Generated by Django 3.2.7 on 2021-10-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liveimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceUser', models.CharField(max_length=100, null=True)),
                ('deviceId', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
